backend:
    name: git-gateway
    branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: zalbastaki
    api_key: 836764511646129
    multiple: true

collections:
    - name: "pages"
      label: "Pages"
      delete: false
      editor:
        preview: false
      files:
        - name: "general"
          label: "General Information"
          file: "src/content/general.md"
          delete: false
          fields:
            - {label: "Logo", name: "logo", widget: "image"}
            - {label: "Email", name: "email", widget: "string"}
            - {label: "LinkedIn", name: "linkedin", widget: "string"}
            - {label: "Github", name: "github", widget: "string"}
        - name: "home"
          label: "Home Section"
          file: "src/content/home.md"
          delete: false
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Subtitle", name: "subtitle", widget: "string"}
            - {label: "Image", name: "image", widget: "image"}
        - name: "about"
          label: "About Section"
          file: "src/content/about.md"
          delete: false
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Content", name: "content", widget: "markdown"}
            - label: "Skills"
              name: "skills"
              label_singular: "Skill"
              widget: "list"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Proficiency Level", name: "proficiency", widget: "number", hint: "Number between 0 and 100."}
        - name: "work"
          label: "Work Section"
          file: "src/content/work.md"
          delete: false
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - label: "Projects"
              name: "projects"
              label_singular: "Project"
              widget: "list"
              fields:
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Description", name: "description", widget: "text"}
                - {label: "Source Link", name: "source", widget: "string", required: false}
                - {label: "Project Link", name: "project", widget: "string", required: false}
                - {label: "Preview", name: "preview", widget: "file"}
        - name: "contact"
          label: "Contact Section"
          file: "src/content/contact.md"
          delete: false
          fields:
            - {label: "Title", name: "title", widget: "string"}